# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70b40ee40f79b0616c0a9d85f9913a764c9bc43eeaa0bfa2e8c3793f655d5479d52c3c4d1907c52cc74ac2e13867f35810e1b603a452fbdacac1d42afd97903b

test:
  secret_key_base: 9cee3f5866e7a5200bc04c794bfc3e4d49aa7e636f2a0070636625f61e301ff20168f7947cd943b284271dcf8b76af0338597d0f6095aa0c1600ff3621ba14bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
